.binder/environment.yml
.ci_support/environment.yml
.github/workflows/push-pull.yml
docs/environment.yml

They fixed it upstream very promptly.
I'm also using the opportunity of such a simple PR to [test out some new centralized CI stuff](https://github.com/pyiron/actions/pull/64), in particular to specify the OSX version to resolve #101

Unpin pytables

---

pyiron_workflow/channels.py
tests/integration/test_parallel_speedup.py
tests/unit/test_channels.py
tests/unit/test_io.py

Simpler connection check

---

.readthedocs.yml

Per @niklassiemer observation in #132.

Try adding a pip install to readthedocs.yml

---

.ci_support/environment-docs.yml
.github/workflows/push-pull.yml
docs/README.md
docs/conf.py
docs/environment.yml
docs/index.rst
docs/source/examples.rst
docs/source/indices.rst

Apply lessons learned updating `pyiron_ontology` and `pyiron_module_template` to get notebooks in the docs, etc.

Polish the docs

---

docs/environment.yml
pyiron_workflow/node.py
pyiron_workflow/snippets/files.py

Resolves review concern: https://github.com/pyiron/pyiron_workflow/pull/160/files#r1449437683

Use h5iostorage directly

---

.binder/environment.yml
.ci_support/environment-notebooks.yml

Because I still haven't fixed the CI to do this automatically for extra requirements and non-main env files
Follows onto #170 -- I failed to check out the right branch before making this change originally 🤦‍♂️

Propagate version change to conda env

---

pyiron_workflow/__init__.py
pyiron_workflow/channels.py
pyiron_workflow/macro.py
pyiron_workflow/node.py
pyiron_workflow/node_library/pyiron_atomistics.py
pyiron_workflow/snippets/testcase.py
tests/unit/test_channels.py

`NOT_DATA` should work like `None`, and therefore should be `else` in the `if`-statement.

`NOT_DATA` should work like None in the if-statement

---

pyiron_workflow/composite.py
pyiron_workflow/node.py
pyiron_workflow/storage.py

As discussed in [the parent branch](https://github.com/pyiron/pyiron_workflow/pull/197/files#r1481891075).
Actually, I super like this after all.

Add a convenience method for reporting importability

---

pyiron_workflow/composite.py
pyiron_workflow/node.py
pyiron_workflow/storage.py
tests/static/demo_nodes.py
tests/unit/test_composite.py
tests/unit/test_node_package.py
tests/unit/test_workflow.py

Fail early if h5io won't be able to re-instantiate a node

---

.binder/environment.yml
docs/environment.yml
tests/unit/test_function.py

Fix test problem created [here](https://github.com/pyiron/pyiron_workflow/pull/213).

[minor] Correct test

---

pyiron_workflow/macro.py
tests/unit/test_macro.py

For the sake of computational efficiency, have macro IO value-link directly to child node IO wherever possible.
As promised in an aside in #268, this slides on top of #276 quite nicely.
Before we _always_ had IO nodes:
```python
@Workflow.wrap_as.macro_node("l", "r")
def double(macro, a, b, c):
return a + b, b + c
m = double()
fig = m.draw(size=(10, 10))
fig.render(filename="before", format="png")  # Or "after"
```
Now, you can see that we only keep the node where it's useful, i.e. where we actually want a node present so the input can be forked with multiple different connections:

[minor] Prune macro IO nodes that don't get forked

---

.binder/environment.yml
.ci_support/environment.yml
docs/environment.yml
pyiron_workflow/io_preview.py
pyiron_workflow/node_library/standard.py
setup.py
tests/unit/test_for_loop.py

I should have been more careful to put the generic changes in separate patches and then merge _those_ changes into the main->JNnodes branch, but this will suffice. Just minor stuff: access points for the new for-nodes, and adding pandas to the requirements.

[patch] Cherrypick changes from merging main into Joerg's branch

---

.github/workflows/daily.yml
.github/workflows/dependabot-pr.yml
.github/workflows/pr-labeled.yml
.github/workflows/pr-target-opened.yml
.github/workflows/push-pull.yml
.github/workflows/weekly.yml

The daily run failed because I was passing it an outdated kwarg. I noticed I had targeted `main` instead of `actions-3.1.0` too, and downgraded `pr-target-opened.yml` version since it I know I bugged it in the latest version.

[patch] Daily patch

---

pyiron_workflow/draw.py

Instead of depending on matplotlib

[patch] Define custom color conversions

---

pyiron_workflow/for_loop.py
pyiron_workflow/function.py
pyiron_workflow/macro.py
pyiron_workflow/node_library/standard.py
pyiron_workflow/transform.py

Not perfect, but closes #344 
Fixing the creator and wrapper docstrings themselves will require first addressing #360

[patch] Better docstrings

---

pyiron_workflow/nodes/for_loop.py

Honestly, I basically just forgot that for-loops are not actually macros. Ideally, this behaviour would come from a shared parent class, like `StaticComposite` analogous to `StaticNode`. Unfortunately, that gives circular imports because the creator object is on `Composite`. Once `Workflow` and `Macro` do not share access to the creator, such an abstraction will be possible. In the meantime, I just tolerate the once-duplicated code.

[patch] :fire: :bug: make sure for-loops re-set their value links like macros

---

pyiron_workflow/nodes/transform.py
tests/unit/nodes/test_transform.py

If you're making something a dataclass node, you can now pass in a dataclass-compliant class that is not yet a dataclass and we'll take care of turning it into one for you. That means you only need `@Workflow.wrap.as_dataclass_node` and not `@Workflow.wrap.as_dataclass_node;@dataclass`. Per Joerg's wishlist.

[patch] Remove the need to double-decorate

---

notebooks/deepdive.ipynb
pyiron_workflow/nodes/composite.py

Introduce a dictionary representation of an entire graph, `Composite.graph_as_node`, connecting full labels to python objects.

[patch] Graph representation

---

pyiron_workflow/node.py
pyiron_workflow/nodes/composite.py
pyiron_workflow/nodes/macro.py

Some stuff slipped through the cracks in earlier PRs

[patch] Remove unused code

---

pyiron_workflow/mixin/storage.py
pyiron_workflow/node.py
pyiron_workflow/storage.py
tests/unit/test_workflow.py

Another step in the process of making `StorageInterface` and ephemeral interface between a node and some standard storage routine.

[patch] Merge `HasStorage` back into `Node`

---

notebooks/deepdive.ipynb
pyiron_workflow/node.py
pyiron_workflow/nodes/composite.py
pyiron_workflow/nodes/for_loop.py
pyiron_workflow/nodes/macro.py
pyiron_workflow/nodes/static_io.py
pyiron_workflow/storage.py
pyiron_workflow/workflow.py
tests/unit/nodes/test_macro.py
tests/unit/test_node.py
tests/unit/test_workflow.py

Rather, take the back end as an argument directly.

[minor] No `storage` property

---

pyiron_workflow/mixin/preview.py
pyiron_workflow/nodes/function.py
pyiron_workflow/nodes/macro.py

To scrape not just the docstring, but the signature and source code as well.

[patch] Extend automatic macro and function node documentation

---

pyiron_workflow/nodes/static_io.py
pyiron_workflow/nodes/transform.py

[patch] Add node colours

---

pyiron_workflow/mixin/run.py
pyiron_workflow/node.py
pyiron_workflow/workflow.py
tests/unit/mixin/test_run.py
tests/unit/test_node.py

Forget about `force_local_execution`; if you want to run it locally just don't set the damned executor. No point in a boolean runtime flag for this, it's already a boolean choice to set the executor or not! Simplify.

[minor] Change run signature

---

pyiron_workflow/storage.py

Define error e if not defined

---

pyiron_workflow/mixin/display_state.py

Add continue for a bit of speed

---

pyiron_workflow/channels.py
pyiron_workflow/io.py
tests/unit/test_channels.py

Apply hints to IO panels

---

pyiron_workflow/mixin/run.py

`mypy` run

---

pyiron_workflow/find.py
pyiron_workflow/topology.py

Nothing of great interest here.

`mypy` topology and find

---

pyiron_workflow/mixin/run.py
pyiron_workflow/nodes/transform.py
pyiron_workflow/workflow.py
tests/unit/test_workflow.py

Mostly just some signature changes to satisfy Liskov substitution, but also relaxing some signature narrowing in `transformer`.

`mypy` signature compliance

---

pyiron_workflow/draw.py

I made the `_Channel` class generic on the workflow `Channel` type, but at this point that is feeling very mundane -- nothing of note here.

`mypy` draw

---

pyiron_workflow/nodes/for_loop.py

I finally need to resort to simply silencing mypy, since the for loop generates type hints based off of type hints in the body node class, but since that class is not known at analysis time it is impossible to satisfy mypy.

`mypy` for_loop

---

pyiron_workflow/io.py
pyiron_workflow/mixin/preview.py
pyiron_workflow/mixin/run.py
pyiron_workflow/nodes/for_loop.py
pyiron_workflow/nodes/function.py
pyiron_workflow/nodes/macro.py
pyiron_workflow/nodes/transform.py

I forgot to check the base mypy branch back out, so ignore the branch name here.

`mypy` finishing touches

---

pyiron_workflow/mixin/preview.py

I also refactored it, because now everywhere we use `inspect.signature` and from my point of view there's not much of a reason to separate the functions.

Refactor preview

---

pyiron_workflow/mixin/run.py
pyiron_workflow/node.py
pyiron_workflow/nodes/function.py
pyiron_workflow/nodes/transform.py

And add that dictionary to the raised exception when there is a readiness error.
Closes https://github.com/pyiron/pyironFlow/issues/43

Build a readiness report from a dictionary

---

pyiron_workflow/__init__.py

Analogous to how we expose the Function and Macro classes for node designers to use in explicit subclass creation.
FYI @pmrv

Expose the For class in the API

---

.github/workflows/push-pull.yml
pyproject.toml

And rely on this configuration at test time

Configure mypy in the pyproject.toml

---

pyiron_workflow/node.py
pyiron_workflow/nodes/composite.py
pyiron_workflow/workflow.py
tests/integration/test_workflow.py
tests/unit/nodes/test_composite.py
tests/unit/test_node.py

If the parent exists.
Closes #682.

Route pushes through parent

---

.binder/environment.yml
.ci_support/environment.yml
.ci_support/lower_bound.yml
.github/workflows/push-pull.yml
docs/environment.yml
pyiron_workflow/channels.py
pyiron_workflow/compatibility.py
pyiron_workflow/executors/cloudpickleprocesspool.py
pyiron_workflow/nodes/macro.py
pyproject.toml

Cf. https://github.com/pyiron/bagofholding/pull/58#issuecomment-3009912344

Drop python 3.10

---

pyiron_workflow/nodes/composite.py
tests/unit/nodes/test_composite.py

Based on the uniform availability among recursive children, and give the setter recursive power.
Closes #699

Compute composite cache usage

---

notebooks/deepdive.ipynb
notebooks/quickstart.ipynb
pyiron_workflow/create.py
tests/integration/test_parallel_speedup.py
tests/integration/test_workflow.py
tests/unit/nodes/test_macro.py
tests/unit/test_workflow.py

Users should just import and use these from their home

Remove external tools from creator

---

pyiron_workflow/node.py
pyiron_workflow/nodes/composite.py
tests/cluster/slurm_test.py
tests/unit/nodes/test_composite.py

If you are a composite and have a running child, you don't get to hit your cache.
Closes #707

No running cache hit

---

pyiron_workflow/mixin/run.py
pyiron_workflow/node.py
pyiron_workflow/workflow.py
tests/integration/test_executors.py
tests/integration/test_workflow.py

When I tried to demo the executor and re-running process, it was extremely fragile. I can only reproduce one of the two problems I ran into (😬), but it pertained to re-running a job that was already running in the same process.
Here I try to robustify some of the re-running capabilities.

Better rerun

---

pyiron_workflow/channels.py
pyiron_workflow/io.py
pyiron_workflow/node.py
pyiron_workflow/workflow.py
tests/unit/test_channels.py
tests/unit/test_node.py

Fail earlier and cleaner if you try to update inputs while already running

Safer input update

---

pyiron_ontology/parser.py

@samwaseda, I don't think you object to the relocation -- we can purge it from `pyiron_ontology` later -- so I'll go ahead and merge without waiting for feedback. But I wanted a nice clear record of where the heck this is coming from 😂

git-copy pyiron_ontology.parser 
