pyiron/pyiron_workflow

pyiron_workflow/node.py

We'll use executors instead, ultimately from pympipool

Remove the references to the server

---

.binder/environment.yml
.ci_support/environment.yml
docs/environment.yml

This is a necessary dependency for atomistics to work, so it will wind up in the env in the long run anyhow (at least until the node libraries are pulled out of the repo), but its appearance as an _explicit_ dependency is just until it correctly appears as an upstream requirement in pyiron_atomistics. Until then I need this so tests don't break meaninglessly.

Add explicit conda env dependency on pyiron-data

---

pyiron_workflow/node.py

Don't have both `fetch` _and_ `update`, rather do both at once.

Better input interface

---

notebooks/workflow_example.ipynb
pyiron_workflow/composite.py
pyiron_workflow/macro.py
pyiron_workflow/node.py
tests/unit/test_function.py
tests/unit/test_macro.py
tests/unit/test_workflow.py

`Composite` instances can now replace one of their children with another node instance or class, as long as that node has no parent or connections and has compatible IO (this PR introduces a tool for coping connections from one node to the other)
Resolves a couple of the TODOs on #7.
```python
@Workflow.wrap_as.single_value_node()
def add_one(x):
result = x + 1
return result
@Workflow.wrap_as.macro_node()
def add_three_macro(macro):
macro.one = add_one()
macro.two = add_one(x=macro.one)
macro.three = add_one(x=macro.two)
macro.inputs_map = {"one__x": "x"}
macro.outputs_map = {"three__result": "result"}
macro = add_three_macro()
replacement = add_three_macro()
print(macro(x=0).result)  # 1 + 1 + 1 = 3
>>> 3
macro.replace(macro.two, replacement) …
```

Allow replacing nodes

---

notebooks/workflow_example.ipynb
pyiron_workflow/channels.py
pyiron_workflow/composite.py
pyiron_workflow/function.py
pyiron_workflow/interfaces.py
pyiron_workflow/io.py
pyiron_workflow/macro.py
pyiron_workflow/meta.py
pyiron_workflow/node.py
pyiron_workflow/util.py
pyiron_workflow/workflow.py
tests/unit/test_function.py
tests/unit/test_macro.py
tests/unit/test_workflow.py

Macros are now walled gardens that have their own IO objects instead of just passing children by reference.
I want to make a final test for ensuring that macro connections get properly recreated after rebuilding the macro IO, but it's working in the demo notebook so this should just be a formality. I expect these changes to make it very easy to extend macros so they run on an executor.
TODO:

No io by reference for macros

---

notebooks/workflow_example.ipynb
pyiron_workflow/channels.py
pyiron_workflow/composite.py
pyiron_workflow/function.py
pyiron_workflow/interfaces.py
pyiron_workflow/io.py
pyiron_workflow/macro.py
pyiron_workflow/meta.py
pyiron_workflow/node.py
pyiron_workflow/util.py
pyiron_workflow/workflow.py
tests/unit/test_channels.py
tests/unit/test_function.py
tests/unit/test_macro.py
tests/unit/test_workflow.py

This will be helpful for making macros into walled gardens that have their own IO instead of simply using references to their children's IO; it will allow us to keep the child node input up-to-date.

Introduce coupling between input channels

---

notebooks/workflow_example.ipynb
pyiron_workflow/composite.py
pyiron_workflow/function.py
pyiron_workflow/macro.py
pyiron_workflow/node.py
pyiron_workflow/topology.py
pyiron_workflow/workflow.py
tests/integration/test_pull.py
tests/unit/test_function.py

Before getting to the meat of it, I updated the API so that all the actual computations using the node get based off the `run` method, which is now made more flexible with some boolean arguments:
- `run(fetch_input_first: bool = True, then_emit: bool = True, force_local_execution: bool = False, check_readiness: bool = True,)` fetches input from connections, raises an error if it's not `ready`, computes (either locally or on an executor), and finally fires the `ran` signal
- `execute()`  to force the computation right here, right now, as-is with `run(fetch_input_first=False, then_emit=False, force_local_execution=True, check_readiness=False)`
- `__call__(*args, **kwargs)` to update input values with (*args and) **kwargs then `run(fetch_input_first=True, then_emit=False)`
- `pull()` to …

Add a `pull()` method

---

notebooks/workflow_example.ipynb
pyiron_workflow/_tests.py
pyiron_workflow/channels.py
pyiron_workflow/composite.py
pyiron_workflow/function.py
pyiron_workflow/interfaces.py
pyiron_workflow/node_library/plotting.py
pyiron_workflow/node_library/standard.py
tests/integration/test_workflow.py
tests/static/demo_nodes.py
tests/static/faulty_node_package.py
tests/static/forgetful_node_package.py
tests/static/not_a_node_package.py
tests/unit/executors/test_cloudprocesspool.py
tests/unit/test_interfaces.py
tests/unit/test_workflow.py

Adds the node registration method back, although at the moment it's just called in `Creator.__init__` so you don't see it.
TODO:
Outside of scope:
- *Actually* supporting all manner of registration types (like a URL) -- I just want infrastructure that will be flexible enough to handle that in the future, not to get it all solved now!
Closes #51

Fix node registration

---

pyiron_workflow/draw.py

Workflows still create IO by reference, but now Macros create their own IO by value and use `DataChannel.value_receiver` to keep values synced with children. Here, we draw these links in the `.draw()` method.
Closes #56.
Result:
```python
@Workflow.wrap_as.single_value_node("y")
def add1(x):
return x + 1
@Workflow.wrap_as.macro_node()
def add2(macro):
macro.one = add1()
macro.two = add1(x=macro.one)
macro.inputs_map = {"one__x": "x"}
macro.outputs_map = {"two__y": "y"}
wf = Workflow("to_draw")
wf.nup = add1(x=0)
wf.m = add2(x=wf.nup)
wf.ndown = add1(x=wf.m.outputs.y)
wf.draw(depth=2)
```

Draw channel links

---

pyiron_workflow/composite.py
tests/integration/test_workflow.py
tests/unit/test_interfaces.py
tests/unit/test_workflow.py

Something silly like `wf.my_node = wf.my_node` used to throw an exception. This is dumb, but sensible things like `wf.user_input = wf.create.standard.UserInput()` used to do the same thing by virtue of the `create` method adding the node already.
Closes #52 
(Ignore the crappy branch name, I just forgot to check out a clean branch before doing the work and accidentally pushed onto the old merged-and-deleted one)

Allow trivial re-assignment

---

pyiron_workflow/atomistics_library/calculatornodes.py
pyiron_workflow/atomistics_library/macronodes.py
pyiron_workflow/atomistics_library/tasknodes.py

This is just so we can `Workflow.register` these files; another PR changing the macros will follow.

Make py files node packages

---

pyiron_workflow/atomistics_library/calculatornodes.py
pyiron_workflow/atomistics_library/macronodes.py
pyiron_workflow/atomistics_library/tasknodes.py

Example:
```
from pyiron_workflow.atomistics_library.calculatornodes import get_emt, calc_with_calculator
from pyiron_workflow.atomistics_library.tasknodes import get_evcurve_task_generator, analyse_structures, generate_structures, get_bulk
wf = Workflow("evcurve")
wf.get_structure = get_bulk(element="Al")
wf.get_task_generator = get_evcurve_task_generator(structure=wf.get_structure)
wf.generate_structures = generate_structures(instance=wf.get_task_generator)
wf.get_calculator = get_emt()
wf.calc_with_calculator = calc_with_calculator(task_dict=wf.generate_structures, calculator=wf.get_calculator)
wf.fit = analyse_structures(instance=wf.get_task_generator, output_dict=wf.calc_with_calculator)
wf.draw()
wf.run()
```
As the workflows in the `atomistics` …

Nodes for the `atomistics` package

---

pyiron_workflow/atomistics_library/macronodes.py

Old: define a generic macro shared by all atomistics workflows leveraging task generators, then define a set of macros each of which instantiates the task generator node and the generic macro node, then connects them and manually re-maps all the task generator input to be available at the macro level.
New: Create a meta-workflow that takes the task generator node as input and returns a macro class in which all the task generator IO has been dynamically re-mapped to be available at the macro level; instantiate this meta-macro once per task generator to get a set of macros.
There is absolutely nothing wrong with the "old" version, it's a perfectly legitimate and legal way to construct a set of macros! Further, the biggest advantage of the "new" way -- that the task generator input is …

Refactor macros

---

.github/dependabot.yml

I just saw the update of action version itself in https://github.com/dependabot/demo and I think this is a nice idea to do!

Handle actions itself in the dependabot updates

---

pyiron_workflow/io.py
pyiron_workflow/util.py
tests/unit/test_io.py
tests/unit/test_util.py

Just adds `to_list()` methods to `DotDict` and `DataIO` so the dictionaries can be case to value lists. The order is explicitly not guaranteed, but it winds up being the order items are added to the underlying dict.
As requested in #38.
Closes #40.

Expose dict values as list

---

pyiron_workflow/node.py
tests/unit/test_node.py

Now you can optionally save the rendered graph in the node's working directory (by default) right when you make the `.draw()` call.
Closes #41

Expose a subset of graphviz.Graph.render options inside Node.draw

---

pyiron_workflow/composite.py
pyiron_workflow/function.py
pyiron_workflow/macro.py
pyiron_workflow/node.py
pyiron_workflow/util.py
pyiron_workflow/workflow.py
tests/unit/test_node.py
tests/unit/test_util.py

Introduces a new metaclass that adds a `__post__` method to classes which is invoked after `__init__` and with the same input. This is leveraged to allow `Node` and its children to run at the end of instantiation (defaults to false, don't run).
Closes #42

Can run right away

---

tests/benchmark/test_benchmark.py
tests/integration/test_parallel_speedup.py
tests/integration/test_workflow.py
tests/unit/snippets/test_dotdict.py
tests/unit/snippets/test_has_post.py
tests/unit/snippets/test_logger.py
tests/unit/snippets/test_singleton.py
tests/unit/snippets/test_testcase.py
tests/unit/test_channels.py
tests/unit/test_composite.py
tests/unit/test_function.py
tests/unit/test_interfaces.py
tests/unit/test_io.py
tests/unit/test_macro.py
tests/unit/test_node.py
tests/unit/test_node_package.py
tests/unit/test_output_parser.py
tests/unit/test_pyiron_workflow.py
tests/unit/test_status_management.py
tests/unit/test_type_hinting.py
tests/unit/test_workflow.py

Since we now only do the CI on python 3.10 and above anyhow!
And always do the unit tests when a tests is `__main__` (Just for you, @samwaseda)

Stop version checking tests

---

pyiron_workflow/channels.py
pyiron_workflow/composite.py

Closes #116 
We still string-code the "__" in examples, but I think that's OK since I expect users to be writing this stuff out in their maps anyhow, only #86 will really help that. 
The while-loop meta node still uses "__" manually, but in a different context so I'm leaving it.

Canonically scoped labels for channels

---

pyiron_workflow/meta.py
pyiron_workflow/node_library/standard.py
tests/integration/test_workflow.py

There are now unhinted nodes for most of the standard python operators. This is a useful prerequisite for #90

Extend standard nodes

---

pyiron_workflow/draw.py

Now that `SingleValue.__getattr__` actually creates a delayed node

Hotfix `draw`

---

pyiron_workflow/snippets/dotdict.py
tests/unit/snippets/test_dotdict.py

Depending on how you tried to get something from a dot-dict, i.e. key errors from item access, attribute errors from attribute access.

Raise the intuitive type of error

---

pyiron_workflow/files.py
tests/unit/test_files.py

Just very minor convenience changes to the filesystem stuff: adds a property `DirectoryObject.is_empty` that checks agains length, and  modifies deletion so you can choose to only delete if it's empty: `DirectoryObject.(self, only_if_empty: bool = False)`

Working dir emptiness check

---

docs/environment.yml
pyiron_workflow/node.py
tests/unit/test_composite.py
tests/unit/test_node.py

Adds a new instance property `Node.root: -> Node` that returns the parent-most node in the node's graph. For the parent-most node or nodes all alone, the `root` is just `self`.
Access to this sort of graph property seems intrinsically nice to me, but in particular I have in mind to use it for specifying nodes as "checkpoints", i.e. points at which the graphs save themselves, by adding a `finally` clause to `Node._finish_run` like:
```python
finally:
if self.is_checkpoint:
self.root.save()
```
I included documentation at the docstring level, but since we don't yet have a use-case (e.g. above) I don't see a need to modify any notebooks or train users on this property.

Expose root node

---

docs/environment.yml
pyiron_workflow/node.py
tests/unit/test_composite.py
tests/unit/test_node.py

Short term intention: for finding location inside a parent-most storage file (related to #165)
Long term intention: for identification independent of storage location (related to #126)
TODO: (super simple, but I've got to run)
EDIT:
Ok, I reduced the scope just a little. This no longer claims to be the `semantic_path` -- an object which may or may not contain super-parent-most-node information in the future -- but just the path _within_ the scope of the current graph. 
Whether and how we allow the _semantic_ grouping (in contrast to operational grouping where data actually flows automatically) of multiple workflow objects is left to the future. In that hypothetical, the `graph_path` becomes merely the tail of the `semantic_path`, but for now we don't close any doors or take any attributes …

Introduce ~semantic~ graph path

---

pyiron_workflow/channels.py
tests/unit/test_channels.py

The scoped label will always be unique, so just store that.
The point is that as we move towards storage and serialization, this gives one less complex object that needs to live on the node.
Right now I lean towards restoring graphs by re-executing from the top, but just not actually re-running nodes who have the same input as they had at their last execution (optional (for slow nodes), evaluated by hash comparison). In that case, we don't _need_ to reload this data as the set will get re-populated at run-time. However, IMO it doesn't hurt to have it serialized, and it will be necessary for finding graph state if we wind up taking a different path to reloading.

Accumulate run signals with scoped labels not objects

---

pyiron_workflow/composite.py
tests/unit/test_macro.py

By setting `running=False` on the local instance _before_ updating the state, we were then re-writing `running=True` when updating the state. Update the flag on the received instance as well, and add a test so the same issue doesn't crop up again.

:bug: stop running

---

pyiron_workflow/channels.py
pyiron_workflow/composite.py
pyiron_workflow/interfaces.py
pyiron_workflow/io.py
pyiron_workflow/macro.py
pyiron_workflow/node.py
tests/unit/test_macro.py

Previously, for remote execution `Composite` passed its children and starting nodes, and then updated those properties with the new instances of them returned in the resulting future. Now, we just ship the entire `self` off and use `__get/setstate__` to update ourselves.
The only subtlety is that when a `Macro` does this, the local instance might be aware of connections to other nodes -- the remote instance has no information about these (it only cares about the current IO values). Thus, when we update the state we need to first grab these connections from the local instance, and then re-map them so the new channel instances returned by the future get used in their place.

Composites pass self instead of children and starting nodes

---

pyiron_workflow/channels.py
pyiron_workflow/composite.py
pyiron_workflow/macro.py
pyiron_workflow/node.py
pyiron_workflow/workflow.py

Purge the remaining references from children to their parents in `__get/setstate__`:
- `Node` purges `parent`, responsibility to (re)store falls on `Composite`
- `Channel` purges `node`, responsibility to (re)store falls on `Node`
- `DataChannel` purges `_value_receiver`, responsibility to (re)store falls on `Macro`
- `Channel` purges `connections`, responsibility to (re)store falls on the `Composite` that is the channel instance's `node.parent` (if any)
This allows us to avoid recursion in serialization, which is treated ok (to a recursion limit if I understand) in `(cloud)pickle`, but not acceptable for `h5io`.

Non-reflexive state

---

notebooks/deepdive.ipynb
pyiron_workflow/__init__.py
pyiron_workflow/channels.py
pyiron_workflow/composite.py
pyiron_workflow/function.py
pyiron_workflow/macro.py
pyiron_workflow/node.py
pyiron_workflow/node_library/pyiron_atomistics.py
pyiron_workflow/node_library/standard.py
pyiron_workflow/snippets/testcase.py
tests/integration/test_parallel_speedup.py
tests/unit/test_channels.py
tests/unit/test_composite.py
tests/unit/test_function.py
tests/unit/test_macro.py
tests/unit/test_node.py
tests/unit/test_workflow.py

The original motivation was to get the non-data data working better with `h5io`, but I actually like the singleton better than using a raw class. Also the `is` comparisons all keep working, since it's literally the same instance.
Defining `__reduce__` allows pickle to get back the exact same global instance defined alongside the singleton class.
After @samwaseda's addition (#185), I start to wonder if this is actually something that would be nice to have generically available in `snippets`?

`NotData` as singleton instead

---

pyiron_workflow/function.py
pyiron_workflow/macro.py

Instead of `abc`.
This isn't particularly important by itself, just aesthetically nice,  but together with the two PRs I opened on `h5io` it lets us save and load with that package since the nodes become pickle-findable.
E.g. we can do this and it works*:
```python
wf = Workflow("some_graph")
wf.inp = wf.create.standard.UserInput(42)
wf.double = 2 * wf.inp
wf.out = wf.create.standard.UserInput(wf.double)
out = wf()
import h5io
h5io.write_hdf5(
fname="stuff.h5",
data=wf,
use_state=True,
overwrite=True,
)
wf_reloaded = h5io.read_hdf5(fname="stuff.h5")
```
*Kind of. `h5io` still borks for some node content, e.g. for the `atomistics` library it complains about some random method on the `Calculator` object that `EMT` inherits from. In contrast, `tinybase` …

Parent decorated nodes to the module their function came from

---

pyiron_workflow/composite.py

To minimize the number of complex instance objects stored in the state

Purge and restore starting nodes from the state

---

pyiron_workflow/interfaces.py
tests/static/nodes_subpackage/subsub_sibling/demo_nodes.py
tests/unit/test_interfaces.py

So that the node package access tree has the same topology as the registered module. There was just a bug. Closes #205

Fix registration

---

pyiron_workflow/job.py
tests/unit/test_job.py

In the long run we want to have queue submission fully integrated with nodes; in the short term, we can get that by making a `pyiron_base` job out of a node. This isn't a permanent solution as it doesn't allow, e.g., sending just one node from a graph off to the queue, only entire graphs (even if they're just one node themself).
Here I introduce two solutions: one defines a new subclass of `TemplateJob` and relies on the node's own storage capabilities to (de)serialize itself (from)to HDF _inside_ the job's working directory. The only true `input` on the job is a string saying what storage backend the node should use (`"h5io"`/`"tinybase"`, per #160); then the user supplies a node instance to the job's `.node` attribute. The executed node can be found in the same place on the job on …

Add and test wrappers for sticking nodes in a pyiron job

---

notebooks/deepdive.ipynb
pyiron_workflow/job.py
pyiron_workflow/node.py
pyiron_workflow/storage.py
tests/unit/test_docs.py
tests/unit/test_job.py
tests/unit/test_macro.py
tests/unit/test_node.py
tests/unit/test_workflow.py

What happened is that I merged the `NodeJob` branch into its parent `storage` branch before making sure the `NodeJob` branch had pulled in its most-up-to-date parent. I didn't notice the incompatibility because the CI was broken due to missing dependencies. Obviously with broken CI I should have been more careful, but also this is sort of a chance I took when I chose to merge _anything_ to _anywhere else_ when the CI was not passing.

Make NodeJob compliant with the storage interface

---

.binder/environment.yml
.ci_support/environment.yml
docs/environment.yml
setup.py

We explicitly depend on it in the job module. We got away without this because the atomistics and contrib dependencies pull base in anyhow.

Explicitly depend on base

---

pyiron_workflow/job.py
tests/unit/test_job.py

To clear room for a simpler NodeJob that _doesn't_ lean on pyiron_workflow's storage implementation

Rename NodeJob to StoredNodeJob

---

pyiron_workflow/function.py

Currently the following function fails:
```python
@single_value_node()
def my_test(a=0):
return None
test = my_test()
test
```
I'm actually not sure if we should make a distinction between returning `None` and not having `return` in the first place, but anyway the current error cannot be understood, so as long as we don't have a more explicit answer, I think we should allow any functions returning `None`.

Allow return None

---

.github/workflows/daily.yml
.github/workflows/dependabot-pr.yml
.github/workflows/pr-labeled.yml
.github/workflows/pr-target-opened.yml
.github/workflows/push-pull.yml
.github/workflows/release.yml
.github/workflows/weekly.yml

Since pyiron actions internally references itself, it's not enough to point to a branch there, that branch needs to internally point to itself! That change was just made, so let's try pointing to such a self-referential branch here.
@pmrv also of interest to you.

[patch] Use the branched version of pyiron/actions

---

pyiron_workflow/job.py
tests/unit/test_job.py

@srmnitc This should solve the issue with the cryptic job names to be more consistent with `pyiron_base`.

[patch] NodeJobOutput: Overload the save function to not change the job name

---

.binder/environment.yml
.ci_support/environment-notebooks.yml
.ci_support/environment.yml
docs/environment.yml
setup.py

So I don't need to think about who's dependency is whose or what is upper-limit locked, and since my bots are not updating the notebook env yaml anyway. Avoids running the whole CI suite N times.

Synchronized dependency bumps

---

pyiron_workflow/macro.py
tests/unit/test_macro.py

I keep making a mistake like this:
```python
@single_value_node("sum")
def addition(a, b):
return a + b
@single_value_node("product")
def multiplication(a, b):
return a * b
@macro_node("result")
def add_and_multiply(macro):
macro.addition = addition(1, 2)
macro.multiplication = multiplication(macro.addition, 5)
return macro.multiplication.outputs.product.value
node = add_and_multiply()
```
The main problem is that in the current implementation it only says `NOT_DATA` does not have `channel`, which doesn't immediately make me understand where the error is coming from.

Add error message for return item without `channel`

---

pyiron_workflow/channels.py
pyiron_workflow/create.py
pyiron_workflow/has_interface_mixins.py
pyiron_workflow/run.py
pyiron_workflow/semantics.py

Just a new parent class to guarantee that `super().__get/setstate__` can always be called. Reduces code duplication. Contributes to #243.

[patch] State mixin

---

pyiron_workflow/channels.py
pyiron_workflow/composite.py
pyiron_workflow/function.py
pyiron_workflow/macro.py
pyiron_workflow/node.py
pyiron_workflow/topology.py
pyiron_workflow/workflow.py
tests/unit/test_channels.py
tests/unit/test_io.py
tests/unit/test_macro.py

This re-parents `Channel` onto `HasLabel` (patch) and renames the `Channel.node` attribute to `Channel.owner` (minor). As we move to composition mixins (#243), this will help break apart where channels depend on their owner being something that "has IO" and where they really depend on it being a node (basically only necessary for node injection on `OutputData`).

[minor] Refactor channel

---

pyiron_workflow/injection.py
tests/unit/test_function.py

For compatibility with iPython, which runs around asking for `_ipython_canary_method_should_not_exist_` left, right, and center.
Closes #253

[patch] Don't let attribute injection work for private variables.

---

tests/unit/snippets/test_files.py
tests/unit/test_io.py

Just correcting some silly little accidents that slipped into the tests.

[patch] Use consistent and canonical cls/self for (non)classmethod

---

pyiron_workflow/node.py
pyiron_workflow/semantics.py

Right now, practically, the parent-most graph object is the parent-most semantic object is a `Node`. There is no reason this needs to be so. These changes make it so that `(semantic/graph)_(root/path)` operate up to the parent-most `Semantic` and `Node` objects respectively -- i.e. a "graph" is a semantic tree whose parent-most object is also a `Node`.

[patch] Honest graph properties

---

pyiron_workflow/composite.py
pyiron_workflow/node.py
pyiron_workflow/storage.py
tests/unit/test_macro.py
tests/unit/test_node.py
tests/unit/test_workflow.py

There are some public-facing methods that are removed, but honestly I'm so confident they weren't used anywhere but the plumbing that I'm still labelling this as a "patch":
- I got rid of the `class_name` attribute and just use `__class__.__name__` directly
- I got rid of the global `pyiron_workflow.storage.ALLOWED_BACKENDS` -- this is now created dynamically as a class attribute based on what mixins are used and can be accessed from `Node.allowed_backends()`
And there are a couple of new interfaces:
- There's some extra public facing methods around `storage_directory`, `storage_path`, etc. which are there to avoid `HasStorage` from inheriting from `Semantic` or `HasWorkingDirectory` but are just re-directions
- `delete_storage` now gives an easy way to delete save files for _all_ …

[patch] Refactor the storage interface

---

pyiron_workflow/node.py
tests/unit/test_node.py

Whatever was broken in the upstream dependency or github image seems to be fixed.

[patch] Revert warning and test for the graphviz call+windows combination

---

pyiron_workflow/function.py
tests/unit/test_function.py

Currently, we jump through some hoops to let users pass `self` as a special argument for `Function` nodes. This didn't show up in the node input, and under the hood the node instance got passed in for that argument. You could do things like this:
```python
@Workflow.wrap_as.function_node()
def Selfish(self, x):
self.some_attribute = 5
return x
n = Selfish()
print(n.inputs.labels)
>>> ["x"]
n(x=42)
print(n.some_attribute)
>>> 5
```
Now we don't, and `self` is treated just like any other `Function` node argument, which means it bumps right into the protection we have in place to stop people from using terms already in the `Function.__init__` signature (this protection allows input to be set as `**kwargs`)
```python …
```

[minor] Function selflessly

---

pyiron_workflow/composite.py
pyiron_workflow/function.py
pyiron_workflow/injection.py
pyiron_workflow/io_preview.py
pyiron_workflow/macro.py
pyiron_workflow/workflow.py

`StaticNode` guarantees that the node's IO specification is available at the class level; here we pull up the IO construction in `Function` to this parent class level, and leverage it also in `Macro` (currently the only other child in the `DecoratedNode(StaticNode)` inheritance tree). The somewhat complex node creation in `Macro` is then simplified to creating value links between the child graph and the macro's IO (already created by the `StaticNode` portion of the `super().__init__` call). As a side effect I got to remove a handful of methods on related classes. This is all purely under-the hood streamlining and required no test modification or UI changes.

[patch] Refactor static node

---

pyiron_workflow/function.py
pyiron_workflow/io_preview.py

And modify which method is abstract, so that child classes don't need to remember to use a cache

[patch] Use lru_cache

---

pyiron_workflow/for_loop.py
tests/unit/test_for_loop.py

A simple call invokes a pull, including pulling the parent tree -- this blows up when the loop is inside a parent scope instead of alone. Since we _know_ these are just user input nodes with direct value connections to the loop macro's scope, we never need to run the pull, or indeed even a fetch the value.
Before, this caused trouble, now it's fine:
```python
@Workflow.wrap.as_macro_node()
def LoopInside(self, x, y):
self.to_list = Workflow.create.transformer.inputs_to_list(
3, y, y, y
)
self.loop = Workflow.create.for_node(
Workflow.create.standard.Add,
iter_on=("obj", "other",),
obj=x,
other=self.to_list
)
return self.loop
li = LoopInside([1, 2], 4)
li().loop
```

:fire: :bug: Don't pull on input nodes

---

.binder/postBuild
.github/workflows/daily.yml
.github/workflows/dependabot-pr.yml
.github/workflows/pr-labeled.yml
.github/workflows/pr-target-opened.yml
.github/workflows/push-pull.yml
.github/workflows/release.yml
.github/workflows/test-latest-release.yml
.github/workflows/weekly.yml

The binder button is patched, so centralized CI targeting is now uniform

[patch] Bump CI target

---

tests/unit/test_output_parser.py

In the output parser test. 
It's just to check that function calls are getting parsed OK into keys, so why use a dependency when anything from the standard library is just as good.

[patch] Replace numpy with math

---

pyiron_workflow/__init__.py
pyiron_workflow/io.py
pyiron_workflow/logging.py
pyiron_workflow/mixin/preview.py
pyiron_workflow/mixin/semantics.py
pyiron_workflow/mixin/storage.py
pyiron_workflow/node.py
tests/unit/mixin/test_preview.py

And change some warnings to info

[patch] Replace warnings.warn with pyiron_snippets logger

---

pyiron_workflow/channels.py
pyiron_workflow/io.py
pyiron_workflow/mixin/has_interface_mixins.py
pyiron_workflow/mixin/injection.py
pyiron_workflow/mixin/semantics.py
pyiron_workflow/node.py
pyiron_workflow/nodes/function.py
pyiron_workflow/nodes/macro.py
pyiron_workflow/nodes/static_io.py
pyiron_workflow/topology.py
pyiron_workflow/workflow.py
tests/unit/test_channels.py

Adds a new property `HasLabel.full_label`; for `HasLabel` it's identical to `label`, but for `Node` it uses the semantic path, and for `Channel` it uses the owner's `full_label` plus the channel `label`.

[patch] Better error messages

---

pyiron_workflow/nodes/standard.py

Add three new nodes to the standard library

[patch] More standard nodes

---

pyiron_workflow/mixin/injection.py
pyiron_workflow/nodes/standard.py

Working on a use case, the injection labels quickly got too long for the filesystem. For very short injection paths it was nice having the provenance of the injection listed right in the name, but it quickly gets silly. Anyhow, the provenance is still there in the graph connections. Now, instead, lean on hashes for the name. The class of the injection is still included, to give at least some quick idea what it's there for when looking at the label.
Also snuck in a hotfix for the last PR.
This is minor because it removes an (unused) public method, and because it may screw up loading old save files that had injected nodes. I don't expect either of these to present a practical problem.

[minor] Hash injection labels

---

pyiron_workflow/nodes/composite.py
pyiron_workflow/nodes/for_loop.py
pyiron_workflow/nodes/macro.py
tests/unit/nodes/test_composite.py
tests/unit/nodes/test_for_loop.py

I ran into a few issues when I tried to put a macro as the body node in a for-loop, just a couple of bugs in the (de)serialization. The actual fixes are just a couple lines, and the rest is tests that fail when the bugfixes aren't there.

[patch] Composite serialization bugs

---

pyiron_workflow/mixin/semantics.py

This is the inverse operation to adding them to the state in __getstate__. Without this, in the subsequent super call, all these children wind up in __dict__.

[patch] :fire: :bug: remove semantic children from the state on __setstate__

---

.github/workflows/daily.yml
.github/workflows/push-pull.yml
.github/workflows/test-latest-release.yml
docs/README.md
notebooks/deepdive.ipynb
notebooks/quickstart.ipynb
pyiron_workflow/__init__.py
pyiron_workflow/create.py
pyiron_workflow/mixin/run.py
pyiron_workflow/node.py
tests/integration/test_workflow.py
tests/unit/nodes/test_macro.py
tests/unit/test_node.py
tests/unit/test_workflow.py

A follow-up to #386 that purges references to `pympipool` in the docs and executor class name.
I also switch to `macos-latest` as `executorlib` uses for its CI.
This removes `PyMpiPoolExecutor` as a `Creator` attribute, changing the API, so not a patch; minor.
EDIT: After merging in the stack, this also removes the default `Creator.Executor`, so we now always specifically ask for ` ProcessPoolExecutor` or `executorlib.Executor` accordingly.

[minor] Executorlib ci and docs

---

pyiron_workflow/node.py

E.g. when comparing a numpy array to None. We continue greedily caching, but if it just doesn't work for some reason, the fallback is to simply not cache. Since the current and cached inputs (along with whether or not they generate a cache hit) is always available to the user, I think we still leave enough data for people to debug cache misses on their own.
Otherwise you need to manually disable caching when input has data types that don't play nicely with comparisons. That means you can work around this, so it's not a critical bug, but it's annoying enough I'll probably release a patch version again this week to get rid of the problem.

[patch] Fail to cache when equality comparison throws an exception

---

notebooks/deepdive.ipynb
pyiron_workflow/mixin/storage.py
pyiron_workflow/node.py
pyiron_workflow/nodes/composite.py
pyiron_workflow/nodes/for_loop.py
pyiron_workflow/nodes/macro.py
pyiron_workflow/nodes/static_io.py
pyiron_workflow/workflow.py
tests/unit/nodes/test_macro.py
tests/unit/test_workflow.py

This introduces a new `Node.storage_backend = "pickle"` that saves nodes to/from pickle files.
This is just a patch, but locally I experimented with the more significant change of making pickle the _default_ back-end, and the entire test suite still ran without a problem, so I'm optimistic the transition will be easy.
In the medium to long term, I still want something like h5 or json for the storage backend, because we want something browsable and (ideally) compatible with version controlling. In the short term, I just want something robust and straightforward.

[patch] Pickle storage backend

---

.binder/environment.yml
.ci_support/environment.yml
.ci_support/lower_bound.yml
docs/environment.yml
notebooks/deepdive.ipynb
pyiron_workflow/__init__.py
pyiron_workflow/mixin/storage.py
pyiron_workflow/node.py
pyiron_workflow/nodes/composite.py
pyiron_workflow/nodes/for_loop.py
pyiron_workflow/nodes/function.py
pyiron_workflow/nodes/macro.py
pyiron_workflow/nodes/static_io.py
pyiron_workflow/nodes/transform.py
pyiron_workflow/workflow.py
pyproject.toml
tests/unit/mixin/test_preview.py
tests/unit/nodes/test_macro.py
tests/unit/nodes/test_transform.py
tests/unit/test_workflow.py

Closes #319.
TODO:
- ~Wait for then bump `pyiron_base`~ I'll make the bump landing-page PR wait, but I want to collapse this stack.

[patch] `as_dataclass_node` pickle compatibility

---

notebooks/deepdive.ipynb
pyiron_workflow/mixin/storage.py
tests/unit/nodes/test_macro.py
tests/unit/test_node.py
tests/unit/test_workflow.py

Don't actually touch the `.storage` object anywhere; use the node-level interface methods

[patch] Don't touch storage

---

pyiron_workflow/node.py
tests/unit/test_node.py

Whatever held us back from loading and then running immediately is a non-issue. Since the order of operations is load --> update input based on (args and) kwargs --> run, this can be useful for loading most of your input and changing one value before starting the autorun.

[patch] Simplify setup and allow loading and running at init

---

pyiron_workflow/mixin/semantics.py
pyiron_workflow/node.py
pyiron_workflow/storage.py
tests/unit/mixin/test_semantics.py
tests/unit/nodes/test_macro.py
tests/unit/test_node.py
tests/unit/test_workflow.py

Moves a bunch of storage routine responsibility off of `Node` and into `storage`. Also moves detailed file responsibilities from `pyiron_snippets.files` to `pathlib` -- `DirectoryObject` has a nasty side effect of creating directories you only want to look at, so until that's fixed we'll do it the old fashioned way.

[minor] Shift responsibility

---

pyiron_workflow/__init__.py
pyiron_workflow/node.py
pyiron_workflow/storage.py
tests/unit/test_node.py
tests/unit/test_storage.py
tests/unit/test_workflow.py

Finished the storage refactoring, allowing non-canonical file paths to be specified, allowing children of `StorageInterface` to take `**kwargs` on their methods, and adding tests and docstrings.
I don't currently expose explicit storage interfaces to the user on the `Workflow.create` menu, but this is probably a good idea in the near future as it's a necessary object for using custom save/load paths. It (and the abstract base `StorageInterface` and convenience generator `available_backends`) is (are) now included in `pyiron_workflow.__init__` though, so it's part of the API and pretty easy to access.

[minor] interface flexibility

---

pyiron_workflow/channels.py
pyiron_workflow/io.py
pyiron_workflow/mixin/has_to_dict.py
pyiron_workflow/node.py
pyiron_workflow/nodes/composite.py
pyiron_workflow/nodes/function.py
pyiron_workflow/nodes/static_io.py
pyiron_workflow/nodes/transform.py

Functionality is similar -- the point is to get a nice JSON representation for child classes. But the public interface is different (hence minor flag), and in particular we don't use `to_dict` which might interfere with other pyiron activities. There's also some changes to exactly the display looks like, but since it's just a nice/useful thing for humans to look at, this is non-critical and can be improved with patches as needed.

[minor] Replace `HasToDict` mixin with `HasStateDisplay` mixin

---

pyiron_workflow/node.py
pyiron_workflow/nodes/function.py
pyiron_workflow/nodes/macro.py
pyiron_workflow/nodes/transform.py

@JNmpi, per our discussion today, I added a private and very generic place for nodes to store extra information that might be useful to users of the node class: the class method `Node._extra_info()`.
Function and macros expose the source code for their `node_function` and `graph_creator`, respectively. Dataclass nodes defined in `__main__` are a little prickly with `inspect.getsource` for reasons I don't understand. Instead of having a lengthy fight with it for this private trial feature, I just directly leveraged the underlying dataclass's `__doc__`, which at least has the standard signature info.
Since this is all private methods for now, we can iterate from here freely in whatever direction is most useful for the GUI without worrying about backwards compatibility.

[patch] Add space for extra information

---

.binder/environment.yml
.ci_support/environment.yml
.ci_support/lower_bound.yml
docs/environment.yml
pyiron_workflow/type_hinting.py
pyproject.toml
tests/unit/test_type_hinting.py

By checking the actual datatype associated with their "magnitude".
I'm also boldly going to try setting the lower bound to the last version and hope it works.
Motivated by https://github.com/pyiron/elaston/pull/45

[patch] Let pint-hinted input values pass through type hinting

---

pyiron_workflow/mixin/semantics.py
pyiron_workflow/nodes/composite.py
tests/unit/mixin/test_semantics.py

Let's the `my_node.semantic_path` retain parent path information even through the `__get/setstate__` cycle (e.g. when (un)pickling)

[patch] Detatched path

---

pyiron_workflow/draw.py

Remove redundant channel definition

---

pyiron_workflow/draw.py

Closes #92
```python
from pyiron_workflow import Workflow, function_node
def add(x, y):
output = x + y
return output
def mul(x, y=2):
raise ValueError
output = x * y
return output
wf = Workflow("draw")
wf.Add = function_node(add, x=1, y=2)
wf.Mul = function_node(mul, x=wf.Add)
wf.run()
```
Btw. does it have a particular reason that node has a color?

[patch] change color when failed

---

pyiron_workflow/draw.py

In the `draw` method I find it extremely difficult to figure out which (especially input) parameters still have to be defined, and I'm sure I'm not the only one feeling this way, but I'm not really sure what would be the best way to distinguish different states. In this example, only `Add__y` has no color, because it's not connected and no value is assigned:
```python
from pyiron_workflow import Workflow, function_node
def add(x, y):
output = x + y
return output
def mul(x, y=2):
output = x * y
return output
wf = Workflow("draw")
wf.Add = function_node(add, x=1)
wf.Mul = function_node(mul, x=wf.Add)
wf.draw()
```
I find it pretty nice because you can immediately see that `Add__y` has to get a value or be connected. But this example is just a suggestion, which I don't consider to be the …

change style depending on the state

---

pyiron_workflow/mixin/run.py
pyiron_workflow/node.py

The only part that's not a pure refactor (I believe), is that now if you encounter an error trying to `_parse_executor` it will still raise the exception, but the node isn't running yet and so it won't set the status to `failed`. Since the executor is some separate object we apply to any function, I feel this is a minor improvement in behaviour, as the node itself hasn't failed for this sort of exception!

[patch] Refactor run

---

pyiron_workflow/io.py
pyiron_workflow/mixin/run.py
pyiron_workflow/node.py
pyiron_workflow/nodes/standard.py
tests/unit/mixin/test_run.py
tests/unit/test_node.py

Now we always use the same callback function, but each step of the `Runnable.run` cycle flexibly lets child classes define kwargs for each step. This lets us stop passing the callback function as an argument and just always use `Runnable._finish_run`.
In `Node`, the new kwargs mean we can move firing the signals over to the `_run_finally` method, and take advantage of this to add a new `failed` output signal.
There's a decent amount going on under the hood here, but for users there is no incompatible changes, just the new signal.

[patch] `Runnable` flexibility and a new output signal

---

pyiron_workflow/io.py
pyiron_workflow/mixin/semantics.py
tests/unit/mixin/test_semantics.py

```python
wf = Workflow("tesile")
wf.Composition = standard_nodes.UserInput("Aluminum")
wf.BoxSize = standard_nodes.UserInput(3 * [1.0e-5])
wf.Seeds = function_node(...)
wf.Grid = function_node(...)
wf.Elasticity = function_node(...)
wf.Plasticity = function_node(...)
wf.Phase = function_node(...)
wf.Homogenization = function_node(...)
wf.Material = function_node(generate_material, elements=wf.Compositions)
```
The previous error message in this situation was: `Could not find attribute Compositions on tesile (Workflow) or among its children (dict_keys(['Composition', 'BoxSize', 'Seeds', 'Grid', 'Elasticity', 'Plasticity', 'Phase', 'Homogenization'])).`. It was sort of difficult to figure out which one I wanted to say for this large number of possibilities. So I added `get_close_matches` …

Get close matches

---

pyiron_workflow/io.py

Code:
```python
def f(a, b, c):
return a
function_node(f, a=1, b=2, d=3)
```
Previous error message:
`ValueError: Tried to set input ['a', 'b', 'd'], but one or more label was not found among available inputs: ['a', 'b', 'c']`
New error message:
`ValueError: {'d'} not found among available inputs: ['a', 'b', 'c']`

Update error message of IO when an inexistent arg is used

---

pyiron_workflow/node.py
tests/unit/test_node.py

It's already there in the underlying storage interface, and in `Node.save`, so here we just extend the exposure to `Node.load`, `.has_saved_content`, and `.delete_storage`.
I.e. 
```python
n = Workflow.create.standard.UserInput(42)
n.save(filename="foo")
n.has_saved_content()
>>> False
n.has_saved_content(filename="foo")
>>> True
n.delete_storage(filename="foo")
n.has_saved_content(filename="foo")
>>> False
```
This will be useful for things automatic saving on failure, etc, where we don't want to overwrite the user's save file and don't necessarily want the node loading at re-instantiation. Just more flexibility overall.

[patch] uniformly expose `filename` in `Node` storage interface.

---

notebooks/deepdive.ipynb
notebooks/quickstart.ipynb
tests/unit/nodes/test_function.py
tests/unit/nodes/test_macro.py
tests/unit/nodes/test_transform.py
tests/unit/test_node.py

Cherry pick the commits from #476 (hence the [unrelated] labels) that stop the local tests from being polluted with recovery files

[patch] Clean tests

---

pyiron_workflow/mixin/run.py
pyiron_workflow/nodes/for_loop.py
tests/integration/test_parallel_speedup.py
tests/integration/test_workflow.py
tests/unit/mixin/test_run.py
tests/unit/nodes/test_for_loop.py

Just a simple thing for parsing executors so they can survive (de)serialization. Now you can say:
```python
my_node.executor = (ProcessPoolExecutor, (), {"max_workers": 4})
```
and similar.
Even more, now it can be _any_ callable returning an executor. That means that the determined user can exploit this to return the same executor instance to multiple nodes in a pickle-compliant way (e.g. by having a separate module that instantiates an executor and a function that imports it).

[patch] Parse executor construction instructions

---

pyiron_workflow/draw.py

For a node that has successfully run and will (with caching) re-run super fast (green), and for a node that is still running (orange).

[patch] Extend @samwaseda's good idea to add colours

---

pyiron_workflow/mixin/run.py

I didn't realize they weren't caught by `Exception`; this way the keyboard interrupt still hits the `Runnable._run_finally`, and in particular `Node` still generates a recovery file

[patch] Catch keyboard interrupts in `Runnable._run`

---

docs/README.md
pyiron_workflow/mixin/run.py
pyiron_workflow/node.py
pyproject.toml

The filesystem interaction is stable and robust (i.e. recovery files get written when things go wrong), which has the knock-on effect that you can scale workflows to remote processes. Support for individual nodes running on remote processes beyond the lifetime of the parent python process is pretty rough, but also there.

[patch] Bump development status to Beta

---

pyiron_workflow/nodes/composite.py

In order to separate the drawing functionality, I extended `graph_as_dict`, so that it returns all the child nodes recursively.
```python
wf = Workflow("wf")
def add(x, y):
result = x + y
return result
def mul(x, y):
result = x * y
return result
def process(macro, x, y):
macro.Add = function_node(add, x=1, y=y)
macro.Mul = function_node(mul, x=x, y=macro.Add)
return macro.Mul
wf.Process = macro_node(process)
d = wf.graph_as_dict
print(d.keys())
print(d["nodes"].keys())
print(d["nodes"]["/wf/Process"].keys())
print(d["nodes"]["/wf/Process"]["nodes"].keys())
print(d["nodes"]["/wf/Process"]["nodes"]["/wf/Process/Add"])
```
Output:
```python
dict_keys(['object', 'nodes', 'edges'])
dict_keys(['/wf/Process'])
dict_keys(['object', 'nodes', 'edges'])
dict_keys(['/wf/Process/Add', …
```

Recursive graph

---

notebooks/quickstart.ipynb

Regarding #500, but I don't want to use the github closing keywords because I'd like to see the docs gen and confirm that this fixes it first.

Nest markdown section headings below the main heading

---

pyiron_workflow/mixin/preview.py
pyiron_workflow/mixin/semantics.py

I.e. dict[str, object] not dict[str:object], as observed by @XzzX in #514

[patch] Fix typos in dict-like type hints

---

pyiron_workflow/channels.py
tests/unit/test_channels.py

Resolve all mypy complaints for the `channels` module.
The main thing here was getting the concept of a conjugate partner for connections all on a good footing -- i.e. a conjugate pair should have the same "flavor" (data or signal, so far), and be of opposite directions (i.e. one each of input and output). Doing this was a learning experience for me in using `typing.Generics`, but was relatively straightforward using a type-var for the partner and then holding it in a class method. For now I stuck as close as possible to the existing implementation, so I use the "flavors" for type-narrowing on the connection partner type.
I briefly played around with actually splitting `Channel` apart to depend on two generics: a "flavor" and a "direction" independently. I like the idea of this because I …

`mypy` channels

---

pyiron_workflow/type_hinting.py

It was necessary for python<3.10, but we dropped support for that, so we can get rid of the ugly, non-public hint.

Drop the private type hint

---

pyiron_workflow/channels.py
tests/unit/test_channels.py

When I proceeded to the `io` module, I realized a problem: Here again we need to be hinting the return of input/output pairs on `disconnect`-like calls. In the `channel` module, we can rely directly on the `Self` and generic types to accomplish this, but for `io` there is no _generic_ way to hint that what gets returned is an I/O pair! This forced me to revisit my [earlier idea](https://github.com/pyiron/pyiron_workflow/pull/534#issue-2776304908) of explicitly decomposing the connection partners (now "conjugate pairs") into a "flavour" channel which should match, and a "direction" channel which should be opposite.
I had to hack away at it a bit to get a representation I liked, but the concrete class definitions are still nearly as succinct, but we have explicit `InputType` and …

`mypy` channels redux

---

pyiron_workflow/channels.py

The instance check to see if a connection candidate has the correct (conjugate) type now occurs only _once_ in the parent `Channel` class. `Channel._valid_connection` is the repurposed to check for validity inside the scope of the classes already lining up, and defaults to simply returning `True` in the base class. `DataChannel` overrides it to do the type hint comparison.
Changes inspired by [conversation](https://github.com/pyiron/pyiron_workflow/pull/533#discussion_r1908526844) with @XzzX.

Refactor connection validity

---

pyproject.toml
tests/unit/nodes/test_composite.py
tests/unit/nodes/test_for_loop.py
tests/unit/nodes/test_function.py
tests/unit/nodes/test_macro.py
tests/unit/test_type_hinting.py

Some of the pieces are commented well, however, since we cannot quarantee good comments I suggest avoiding commented-out code entirely to avoid confusion.

avoid commented-out code (ruff-ERA)

---

pyiron_workflow/mixin/semantics.py
pyiron_workflow/nodes/composite.py
pyiron_workflow/workflow.py
tests/unit/mixin/test_semantics.py
tests/unit/test_workflow.py

Resolves most of the mypy complaints in the `semantics` module. The two main changes are to make `SemanticParent` a generic, and purging the `ParentMost`. 
For the former, the reliance on `Generic` allows us to specify a type for the children, which is leveraged in `Composite(SemanticParent[Node],...)`. In the long run, I believe this should be narrowed to `SemanticParent[StaticNode]`, but that's related to #360 and so I want to hold off for now.
For the latter, the only place this was really relevant was in `Workflow`. It was anyhow not a great solution, since in principle we _do_ want `Workflow` to be able to have semantic parents...just not workflow graph parents. In the absence of `ParentMost`, it is simply up to subclasses of `Semantic` to update their `parent` setter if they want …

`mypy` semantics

---

pyiron_workflow/mixin/has_interface_mixins.py
pyiron_workflow/mixin/semantics.py
pyiron_workflow/node.py
pyiron_workflow/nodes/composite.py
tests/unit/mixin/test_semantics.py

Some refactoring, namely getting rid of the `HasParent` interface (which was only used in a single place, `Semantic`, which can simply have that as part of _its_ interface) and breaking `SemanticParent` out of the `Semantic` inheritance tree. These made it easier to then make `Semantic` generic on its parent type, so that type narrowing in `Node(..., Semantic["Composite"], ...)` gives us helpful type narrowing.
I think `mypy --strict` will still complain about the typevar definitions,
```python
ParentType = TypeVar("ParentType", bound="SemanticParent")
ChildType = TypeVar("ChildType", bound="Semantic")
```
This is because the bounds are generic and we leave the resolution implicitly as `typing.Any`. At present I'm not concerned about this because (a) let's get `mypy` happy before worrying …

Semantics generic parent

---

pyiron_workflow/mixin/run.py
pyiron_workflow/nodes/transform.py
pyiron_workflow/storage.py
pyiron_workflow/workflow.py
tests/unit/test_workflow.py

Nothing of particular note here

`mypy` storage

---

pyiron_workflow/io.py
pyiron_workflow/mixin/display_state.py
pyiron_workflow/mixin/has_interface_mixins.py
pyiron_workflow/mixin/injection.py
pyiron_workflow/mixin/run.py
pyiron_workflow/mixin/single_output.py
pyiron_workflow/node.py
pyiron_workflow/nodes/macro.py
pyiron_workflow/nodes/transform.py
pyiron_workflow/storage.py
pyiron_workflow/workflow.py
tests/unit/test_io.py
tests/unit/test_workflow.py

Makes `HasIO` generic on the type of data output panel it returns. A new generic class is introduced for the data outputs panel, but intermediate classes are trimmed elsewhere. Also tacked on some type hint fixes where the panels are used.

Generic `HasIO` classes to specify data output panel types

---

pyiron_workflow/mixin/preview.py
pyiron_workflow/nodes/transform.py

The potential usage is limited to transform and for-loop modules, and the extra layer of misdirection does not feel worth the very minimal reduction in code duplication

Remove preview helper method

---

pyiron_workflow/nodes/composite.py
tests/unit/nodes/test_composite.py

To match return in parent class. Disconnections were only ever used in the test case, and users are always free to disconnect and _then_ remove if they want to capture the broken connections explicitly.

Change return on Composite.remove_child

---

pyiron_workflow/nodes/composite.py
pyiron_workflow/nodes/macro.py
pyiron_workflow/workflow.py

Instead of only returning the replaced node.

Return both nodes on replacement

---

pyiron_workflow/nodes/macro.py
tests/unit/nodes/test_macro.py

With accompanying change to applications/invocations, type hint narrowing, and docstrings

Make Macro.graph_creator a normal method

---

pyiron_workflow/channels.py

No need to hint the property, and because an `OutputDataWithInjection` can take an `OutputData` as a value receiver, the hint on the property should be the receiver type, not self.

Fix value receiver hinting

---

pyiron_workflow/mixin/preview.py
tests/unit/mixin/test_preview.py

I was trying to get full type hints by using `inspect` instead of `get_type_hints`.
Well, this being said I'm painfully aware of the fact that the tests fail, but I don't really know why XD The problem comes from the fact that somehow `type_dict["return"]` turns the return type into a string, so for example instead of `tuple[float, float, float]` you get `"tuple[float, float, float]"`, even though if I copy and paste the code snippet I can get the correct type. Is there any transformation that takes place before `preview_io`?

Use inspect in order to get type hint metadata

---

pyiron_workflow/storage.py
tests/unit/test_node.py
tests/unit/test_storage.py
tests/unit/test_type_hinting.py

Patching #579 
In particular, when `storage.available_backends` receives a `StorageInterface` instance it needs to return that instance _and_ the standard backend(s), because interfaces may have states so a simple type check is not sufficiently details. And when `storage.available_backends` receives a string, it should _not_ return two copies of the standard backend(s) because the string can't carry any state so the default standard backend must be identical.
Honestly, the whole thing could use more simplification, but I am again uninterested in perfecting it while a new storage infrastructure is currently being worked on. In the mean time, this on top of #579 anyhow moves things in a nice direction in the meantime.

Fix comparisons tests

---

.github/workflows/push-pull.yml
pyiron_workflow/mixin/semantics.py
pyiron_workflow/storage.py
tests/unit/test_node.py
tests/unit/test_storage.py
tests/unit/test_type_hinting.py

fix
```
pyiron_workflow/mixin/semantics.py:100: error: Non-overlapping container check (element type: "Semantic[ParentType]", container item type: "str")  [comparison-overlap]
pyiron_workflow/storage.py:316: error: Non-overlapping equality check (left operand type: "type[PickleStorage]", right operand type: "StorageInterface")  [comparison-overlap]
```
and enable corresponding `mypy` check.

fix faulty comparisons

---

.binder/environment.yml
.ci_support/environment.yml
docs/environment.yml
pyiron_workflow/create.py
pyproject.toml
tests/integration/test_workflow.py

Add executorlib container

---

pyiron_workflow/mixin/single_output.py
tests/integration/test_workflow.py
tests/unit/test_node.py

Just conceptually errors being raised from `__getattr__` ought to be this way anyhow, not `ValueError`. But more importantly, raising a `ValueError` instead of an `AttributeError` meant that the builtin `hasattr` method couldn't properly return `False` when the lookup failed due to not having an unambiguous `.channel` attribute to which to delegate the lookup.
Since we redirect `__getitem__` to `__getattr__`, maybe `AmbiguousOutputError` should have dual inheritance with `AttributeError` _and_ `KeyError`. However, this PR is really to address the key problem that `hasattr` is failing. Since I didn't have to touch the rest of the test suite, it seems to have accomplished it without any other side effects. I'd like to delay further modifications until a clear need appears.

Reparent AmbiguousOutputError onto AttributeError

---

pyiron_workflow/nodes/transform.py
tests/unit/nodes/test_transform.py

type(cls) is only equal to type if no other meta class has been used. This includes classes derived from ABC, so it is a bit inconvenient. Using the instance check however seems to work in these cases.

Use instance check instead of equality in as_dataclass_node

---

pyiron_workflow/nodes/composite.py
tests/unit/nodes/test_composite.py
tests/unit/nodes/test_transform.py

I.e.
```python
import pyiron_workflow as pwf
wf = pwf.Workflow("empty")
wf()
>>> {}
```
Closes https://github.com/pyiron/pyironFlow/issues/48

Permit empty graphs

---

pyproject.toml

Otherwise pip install . will not run in a clean env.
@liamhuber As per our ealier mails, but not sure if this is how you intend things to be.

Add pyiron_snippets/pint to build requires

---

pyiron_workflow/node.py
pyiron_workflow/nodes/for_loop.py
tests/unit/nodes/test_for_loop.py

Closes #610 
Basically instead of _always_ rebuilding the child graph, we only rebuild it on cache misses. This is still a bit too aggressive of a rebuild, since in principle we only need to rebuild when the lengths of things we're iterating on change. Nonetheless, it's a simple step in the right direction.
@pmrv does the architecture look ok? Also, I'd like to add a test for this, but all I can think of is iterating over `standard_nodes.Sleep` and making sure it's faster the second time, but I don't really want to make such a slow test -- do you see a more clever route?

Caching `For`

---

pyiron_workflow/node.py
pyiron_workflow/nodes/for_loop.py
tests/integration/test_workflow.py

[@Tara-Lakshmipathy pointed out](https://github.com/pyiron/pyironFlow/issues/104#issuecomment-2718649284) that running a particular node doesn't actually push downstream when those nodes are inside the scope of a parent. Indeed, he's right and there was no simple flag or whatever to enable this! 
So here `Node.run` is modified to force signals to emit from nodes who don't have a parent (the existing behaviour) OR who do but whose parent is not itself currently running (and thus managing execution flow) (the new behaviour).

Emit signals when running a child directly

---

pyiron_workflow/__init__.py
pyiron_workflow/mixin/preview.py
pyiron_workflow/nodes/function.py
tests/unit/nodes/test_function.py

This adds a `scope` parameter to the `to_function_node` converter that is used by the underlying `ScrapesIO` class to parse string type hints into python objects when that conversion context would otherwise be missing from the `inspect.signature(..., eval_str=True)` call.

Scoping type hints

---

pyiron_workflow/__init__.py
pyiron_workflow/mixin/preview.py
pyiron_workflow/nodes/for_loop.py
pyiron_workflow/nodes/function.py
pyiron_workflow/nodes/transform.py
tests/integration/test_workflow.py
tests/unit/nodes/test_for_loop.py
tests/unit/nodes/test_function.py
tests/unit/nodes/test_transform.py
tests/unit/test_storage.py

Sometimes we don't have access to the function we want to node-ize to decorate it, and writing out a wrapping function can be annoying, so (under a subset of circumstances) this is a shortcut:
```python
>>> import numpy as np
>>> from pyiron_workflow.nodes.function import to_function_node
>>>
>>> Trapz = to_function_node("Trapz", np.trapz, "trapz")
>>> Trapz.preview_io()
{'inputs': {'y': (None, NOT_DATA),
'x': (None, None),
'dx': (None, 1.0),
'axis': (None, -1)},
'outputs': {'trapz': None}}
```
- The function must be inspectable
- e.g. `numpy.arange` fails this requirement
- The function must not use protected or argument names
- e.g. variadics `*args` and `**kwargs`
- ~The function's annotations must be universally accessible~
- ~In most cases this means they are restricted to no …

Inline Function class creator

---

.binder/environment.yml
.ci_support/environment.yml
.github/workflows/push-pull.yml
docs/environment.yml
pyproject.toml
tests/unit/mixin/test_preview.py

Including extra build packages since [conda-forge dropped setuptools and wheel](https://conda-forge.org/news/2024/08/21/sunsetting-pip-deps/?utm_source=chatgpt.com)

Configure for py3.13

---

pyiron_workflow/channels.py
pyiron_workflow/io.py
pyiron_workflow/nodes/composite.py
pyiron_workflow/workflow.py
tests/unit/nodes/test_composite.py
tests/unit/nodes/test_function.py
tests/unit/test_channels.py
tests/unit/test_io.py

In the places where we previously copied connections from one node/panel/channel to another, now they are hard-moved. I.e. the connections are _removed_ from the copyee, and the copyer first disconnects all it's connections then takes on those of the copyee.
Since this functionality is almost never used, this had surprisingly little impact. The main use-case is in-situ replacement, but there its obviously totally fine to have this type of full and hard copy.
This is in preparation for #502 -- in the case that the copyer already had an input connection, or that the copyee already had an output connection, a plain copy would otherwise result in an input somewhere getting two inputs.

"Move", don't "copy" connections

---

pyiron_workflow/node.py
tests/integration/test_recovery.py

When re-running a workflow with a child who is running.
Closes #676

Raise a readiness error

---

pyiron_workflow/mixin/lexical.py
pyiron_workflow/node.py
tests/integration/test_workflow.py
tests/unit/mixin/test_lexical.py
tests/unit/nodes/test_macro.py
tests/unit/test_workflow.py

Lexical is still generic on the type hint, but only for type hinting not on the actual parent class object. We accomplish this by shifting the entire responsibility of typing/cylcicity/parentage over to the parent -- so LexicalParent still needs to explicitly know its child type, but this way it's a unidirectional dependency and we can get rid of the local import of `Composite` inside `Node`.
Closes #680

Remove `Lexical.parent_type`

---

pyiron_workflow/mixin/lexical.py
tests/unit/mixin/test_lexical.py

Recursively if they are also themselves a lexical parent.
This is particularly handy for cleaning up file trees if lexical objects leveraged their `.as_path` feature to populate the file system (as nodes do).

Let `Lexical` objects clean their associated path

---

pyiron_workflow/workflow.py
tests/cluster/slurm_test.py
tests/unit/test_workflow.py

If you try to `Workflow.run_in_thread` and the executor is _already_ a `ThreadPoolExecutor` or instructions for one, just let it be and don't `None` it when you're done.
This is useful if you started a workflow in threaded mode, saved it, and reloaded it later -- we can `run_in_thread` again without any headaches. 
Closes #705 
There is some possibility for implicit complication where a user is expecting a simple thread pool executor and accidentally gets another one that had setting set (e.g. `max_workers > 1`), but I struggle to imagine how this will be particularly harmful, and it is easy enough to just set your executor back to `wf.workflow = None` before calling `wf.run_in_thread()` again.

Let threadpools be

---

pyiron_workflow/mixin/lexical.py
pyiron_workflow/node.py
pyiron_workflow/storage.py
tests/unit/mixin/test_lexical.py
tests/unit/test_storage.py

First item in the list of #735

Add `mkdir` to `as_path`

---

pyiron_workflow/node.py
pyiron_workflow/overloading.py
tests/unit/test_overloading.py

This overloads the `Node.load` method so it can be called directly from the class level (with a filename). Per #758, this lets you more succinctly load workflows.

Better loading
